name: build-grpc-php-plugin-binary

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# version of grpc repository to make compile
env:
  GRPC_REPO_VERSION: "v1.56.0"
  # DISABLE_BAZEL_WRAPPER: true
  # specify bazel version
  OVERRIDE_BAZEL_VERSION: "5.0.0"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # only build when commit message contain '[build]' string
    if: contains(github.event.head_commit.message, '[build]')
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: "grpc/grpc"
          ref: ${{ env.GRPC_REPO_VERSION }}
          submodules: recursive
          path: 'grpc'

      - name: Install Basilisk
        run: |
          wget https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-amd64
          chmod a+x bazelisk-linux-amd64
          sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel

      # Runs a single command using the runners shell
      - name: make build
        run: ls -la $ANDROID_NDK_HOME && cd grpc && /usr/local/bin/bazel build src/compiler:grpc_php_plugin
        # run: $sudo apt install cmake make && cd $GITHUB_WORKSPACE/grpc && mkdir -p cmake/build && cd cmake/build && cmake ../.. && make grpc_php_plugin

      # Runs a set of commands using the runners shell
      # - name: show result
      #   id: show_result
      #   run: |
      #     [ -f "$GITHUB_WORKSPACE/grpc/cmake/build/grpc_php_plugin" ] && exit 0 || exit 1

      - name: publish release
        uses: softprops/action-gh-release@v1
        if: ${{ success() }}
        with:
          files: ./grpc/bazel-bin/src/compiler/grpc_php_plugin
          tag_name: ${{ env.GRPC_REPO_VERSION }}
          name: grpc-php-plugin